DROP TABLE IF EXISTS comments;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS articles;
DROP TABLE IF EXISTS users;

CREATE TABLE users (
    id INTEGER NOT NULL ,
    username VARCHAR(64) ,
    firstName VARCHAR(64) ,
    lastName VARCHAR(64) ,
    email VARCHAR(64) ,
    password VARCHAR(255),
    description text,
    birthday date ,
    avatar_path text ,
    PRIMARY KEY(id)
);

CREATE TABLE articles (
    id INTEGER NOT NULL ,
    title text,
    author_id INTEGER,
    abstract text,
    content text,
    create_time timestamp default current_timestamp,
    edit_time timestamp,
    category  VARCHAR(64),
    icon_path text,
    PRIMARY KEY(id),
    FOREIGN KEY (author_id) references users (id) ON DELETE CASCADE

);

CREATE TABLE comments (
    id INTEGER NOT NULL  PRIMARY KEY,
    parent_id INTEGER,
    article_id INTEGER,
    user_id INTEGER,
    content TEXT,
    time TIMESTAMP,
    FOREIGN KEY(article_id) REFERENCES articles(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE,
    FOREIGN KEY(parent_id) REFERENCES comments(id) 
);

CREATE TABLE likes (
    article_id INTEGER,
    user_id INTEGER,
    PRIMARY KEY(article_id, user_id),
    FOREIGN KEY(article_id) REFERENCES articles(id) ON DELETE CASCADE,
    FOREIGN KEY(user_id) REFERENCES users(id) ON DELETE CASCADE
);

INSERT INTO users (username, firstName, lastName, email, password, description, birthday, avatar_path)
VALUES
  ('demo1', 'demoFirst', 'demoLast', 'demo@example.com', '$2b$10$5YW69v4PQ.0QNZ2spwIpteWiSdmtIOJLm4pWylHWWTNLVYQ2nLfV6', 'Hi, I am only used for Blog Demo!', '2024-01-01', '/src/lib/assets/avatar/avatar4.jpg'),
  ('CS719', 'CS719First', 'CS719Last', 'CS719@example.com', '$2b$10$5YW69v4PQ.0QNZ2spwIpteWiSdmtIOJLm4pWylHWWTNLVYQ2nLfV6', 'I LOVE CS719!', '2024-01-01', '/src/lib/assets/avatar/avatar5.jpg'),
  ('CS718', 'CS718First', 'CS718Last', 'CS718@example.com', '$2b$10$5YW69v4PQ.0QNZ2spwIpteWiSdmtIOJLm4pWylHWWTNLVYQ2nLfV6', 'I LOVE CS718!', '2024-01-01', '/src/lib/assets/avatar/avatar6.jpg'),
  ('Kiko', 'Kiko', 'Chen', 'kiko@gmail.com', '$2b$10$5YW69v4PQ.0QNZ2spwIpteWiSdmtIOJLm4pWylHWWTNLVYQ2nLfV6', 'HAPPY CODING!', '2024-01-01', '/src/lib/assets/avatar/avatar14.jpg'),
  ('Rita', 'Rita', 'Wang', 'Rita@gmail.com', '$2b$10$5YW69v4PQ.0QNZ2spwIpteWiSdmtIOJLm4pWylHWWTNLVYQ2nLfV6', 'HAPPY CODING!', '2024-01-01', '/src/lib/assets/avatar/avatar1.jpg'),
  ('Lesley', 'Lesley', 'Gao', 'Lesley@gmail.com', '$2b$10$5YW69v4PQ.0QNZ2spwIpteWiSdmtIOJLm4pWylHWWTNLVYQ2nLfV6', 'HAPPY CODING!', '2024-01-01', '/src/lib/assets/avatar/avatar3.jpg'),
  ('Alan', 'Alan', 'Gu','Alan@gmail.com','$2b$10$5YW69v4PQ.0QNZ2spwIpteWiSdmtIOJLm4pWylHWWTNLVYQ2nLfV6', 'HAPPY CODING','2024-01-01','/src/lib/assets/avatar/avatar2.jpg'),
  ('Tyne', 'Tyne', 'Crow', 'Tyne@gmail.com','$2b$10$VZZMs0Qcwas4/PLu7daHpOmzrhAYP2CR9/eYN17ZqYh4/P5.jTKVG','🐾😺Turning every moment into a purr-fectly delightful experience🐾😺','2024-01-01','/src/lib/assets/avatar/avatar10.jpg' ),
  ('Yucheng', 'Yucheng', 'Tu','Yucheng@gmail.com', '$2b$10$Ux54O.J0P40WDeWWYi8WBup.tHqkiKcuAoS65SEHYHp/5IsV0fSKS','🌸💻🎉コーディングを楽しんで！ (Happy coding!🌸💻🎉)','2024-01-01','/src/lib/assets/avatar/avatar9.jpg'),
  ('Andrew', 'Andrew', 'Meads','Andrew@gmail.com', '$2b$10$1MBGW8cc03mqrG.gDMDMKuoD9Hx3CYPEziU8VT.XxNOXsmHB/BRPu','🐱⚡ピカチュウ、かみなりのいし！(Pikachū, kaminari no ishi!🐱⚡)','2024-01-01','/src/lib/assets/avatar/avatar12.jpg');


INSERT INTO articles (title, author_id, abstract, content, create_time, edit_time, category, icon_path)
VALUES

('Hidden Gems of Southeast Asia', 1, 'From the pristine beaches of Palawan to the ancient temples of Bagan, this travelogue unveils the regions hidden gems, offering a unique blend of cultural richness and natural beauty.', 'Southeast Asia, with its diverse landscapes and vibrant cultures, beckons intrepid travelers seeking authentic experiences beyond the beaten path. Begin your adventure in Palawan, Philippines, where turquoise waters and secluded coves create a tropical paradise. Explore the historical charm of Luang Prabang in Laos, a UNESCO World Heritage site adorned with ancient temples and French colonial architecture. As you venture into the heart of Cambodia, marvel at the enigmatic temples of Bagan, rising majestically from the mist. Dive into the cultural tapestry of Myanmars Shan State, where hill tribes preserve traditions unchanged by time. This journey transcends the ordinary, revealing the true essence of Southeast Asia for those with a passion for exploration.', "2023-01-02", "2023-01-03", 'Asia', '/articles/SouthAsia1.jpg'),
('Epic Road Trip: Exploring the American Southwest', 2, 'From the majestic Grand Canyon to the surreal beauty of Antelope Canyon, this travel narrative captures the essence of freedom on the open road, immersing you in the awe-inspiring wonders of the desert.', 'The American Southwest unfolds like a vivid canvas of red-rock canyons, sprawling deserts, and iconic landmarks. Begin your journey at the Grand Canyon, where the sheer magnitude of natures artistry leaves an indelible mark. Traverse the legendary Route 66, absorbing the nostalgic charm of small towns and roadside attractions. Antelope Canyon beckons with its sculpted sandstone walls, capturing ethereal beams of sunlight. Monument Valley, with its towering mesas, epitomizes the spirit of the American West. Conclude your adventure in the artistic enclave of Santa Fe, where adobe architecture and vibrant art scenes blend seamlessly. This road trip transcends mere travel; it becomes a pilgrimage through the heart of the American Southwest, where every curve in the road reveals a new chapter in the unfolding story of the desert.', '2023-01-02', '2023-01-02', 'America', '/articles/Epic2.jpg'),
('Cultural Tapestry of Kyoto: Temples, Tea, and Tradition', 1, 'This travel narrative explores the historic temples, traditional tea ceremonies, and the cultural nuances that make Kyoto a captivating destination for those seeking a glimpse into Japans rich heritage.', 'Kyoto, the cultural heart of Japan, invites travelers to step into a world where the past and present harmonize seamlessly. Begin your exploration at Kinkaku-ji, the Golden Pavilion, a Zen Buddhist temple adorned in gold leaf. Wander through the iconic Fushimi Inari Shrine, famous for its thousands of torii gates. Partake in a traditional tea ceremony, savoring matcha in the serene surroundings of tea houses nestled within lush gardens. Discover the art of ikebana (flower arranging) and witness the beauty of geisha performances in Gion.', '2023-03-09', '2023-03-09', 'Asia', '/articles/Kyoto.jpg'),
('Island Hopping in the Mediterranean: A Tapestry of Cultures', 3, 'From the historic shores of Crete to the glamour of Capri, this exploration captures the essence of island life in one of the worlds most enchanting regions.', 'The Mediterranean Sea cradles a collection of islands, each with its unique charm. Start your journey on the largest Greek island, Crete, where the Minoan ruins echo tales of antiquity. Cruise to the picturesque Santorini, where white-washed buildings cling to cliffs overlooking the deep blue Aegean. Corsica, with its rugged landscapes, invites exploration of ancient citadels and charming villages. Glide to Sardinia, where emerald waters and pristine beaches beckon. Conclude your odyssey on the glamorous shores of Capri, an Italian gem known for its stunning coastline and luxurious ambiance. Island hopping in the Mediterranean is not just a vacation; it is a cultural immersion. Each island, with its own history and allure, contributes to a mosaic of experiences that define the Mediterraneans timeless allure.', '2023-02-01', '2023-02-01', 'Europe', '/articles/Island.jpg'),

('In the Lap of the Himalayas: Trekking Through Nepals Annapurna Circuit', 4, 'This travelogue explores the awe-inspiring landscapes, ancient villages, and the spiritual allure that defines one of the worlds most iconic trekking routes.', 'The Annapurna Circuit, a classic trek in the heart of the Himalayas, promises an unforgettable adventure. Begin in the bustling city of Kathmandu before embarking on a trek that takes you through diverse landscapes—from terraced fields and subtropical forests to high alpine meadows. Encounter traditional Gurung and Thakali villages, where hospitality is as warm as the traditional tea served. As you ascend to Thorong La Pass, the highest point of the circuit, marvel at panoramic views of the Annapurna and Dhaulagiri mountain ranges. This trek is not just a physical journey but a spiritual odyssey through the breathtaking landscapes of Nepal.', '2023-02-03', '2023-02-03', 'Asia', '/articles/Himalaya.jpg'),
('Beyond Machu Picchu: Exploring the Mysteries of Peru', 5, 'Venture beyond the iconic ruins of Machu Picchu and uncover the rich tapestry of culture, history, and natural wonders that define Peru.', 'Peru is a land of ancient civilizations and breathtaking landscapes. Start your exploration in Cusco, the former capital of the Inca Empire, where Spanish colonial architecture meets indigenous traditions. Journey through the Sacred Valley, dotted with Inca ruins and indigenous markets. Discover the mystical Nazca Lines from above, a UNESCO World Heritage site shrouded in mystery. Traverse the Amazon rainforest, home to an incredible array of biodiversity. Conclude your journey at Lake Titicaca, the highest navigable lake in the world, where indigenous communities preserve age-old traditions. Peru is a kaleidoscope of experiences waiting to be unveiled.', '2023-02-07', '2023-02-07', 'America', '/articles/machu.jpg'),
('Chasing the Northern Lights: A Winter Wonderland in Lapland', 6, 'This travel tale captures the enchantment of husky sledding, ice hotels, and the unique cultural experiences that make Lapland a dream destination for winter enthusiasts.', 'Lapland, situated in the northern reaches of Europe, transforms into a winter wonderland where the Northern Lights steal the show. Begin your journey in Rovaniemi, the official hometown of Santa Claus, and embark on a thrilling husky safari through snow-covered forests. Experience the surreal beauty of the IceHotel in Jukkasjärvi, where rooms and sculptures are crafted entirely from ice. Explore the Sami culture, indigenous to Lapland, and savor traditional dishes around a roaring fire. The Northern Lights, painting the night sky in hues of green and pink, create an otherworldly atmosphere that defines the magic of Lapland.', '2023-02-08', '2023-02-8', 'Europe', '/articles/NorthernLight.jpg'),
('Cruising the Galápagos: A Wildlife Expedition in Ecuador', 4, 'Embark on a once-in-a-lifetime expedition to the Galápagos Islands, an ecological haven that inspired Charles Darwins theory of evolution. ', 'The Galápagos Islands, a UNESCO World Heritage site, offer a glimpse into a world untouched by time. Board a cruise to explore the diverse ecosystems and encounter the fearless wildlife that inspired Darwins groundbreaking theories. Snorkel alongside playful sea lions, observe giant tortoises in their natural habitat, and marvel at the vibrant marine life. Learn about ongoing conservation efforts aimed at preserving the delicate balance of this ecological paradise. The Galápagos Islands provide an immersive experience in nature, where each moment is a lesson in the interconnectedness of life on Earth.', '2023-02-07', '2023-02-07', 'America', '/articles//wildlife.jpg'),
('The Silk Road Odyssey: Traversing Ancient Trade Routes', 5, 'This travel narrative unravels the cultural tapestry, architectural marvels, and diverse landscapes that define this epic transcontinental expedition.', 'The Silk Road, once a bustling network of interconnected trade routes, has left an indelible mark on the history of human civilization. Begin your odyssey in Xi''an, China, where the Terracotta Army stands testament to the region''s rich past. Traverse through Central Asia, discovering the Islamic architecture of Samarkand and Bukhara. Cross the deserts of Turkmenistan and the rugged landscapes of the Caucasus, reaching the historic city of Istanbul, where East meets West. Explore the ancient trading posts, caravanserais, and cultural crossroads that shaped the Silk Road, uncovering the shared heritage of civilizations along this historic route.', '2023-03-01', '2023-03-01', 'Asia', '/articles/SilkRoad.jpg'),
('Safari Serenity: Exploring the Wildlife Reserves of South Africa', 3, 'This travelogue captures the thrill of game drives, encounters with diverse ecosystems, and the conservation efforts that make South Africa a premier destination for wildlife enthusiasts.', 'South Africas wildlife reserves offer a front-row seat to the mesmerizing spectacle of the animal kingdom. Begin your journey in Kruger National Park, one of the worlds most renowned safari destinations, and embark on game drives to spot lions, elephants, leopards, rhinos, and buffaloes—the "Big Five." Explore the diverse ecosystems of Addo Elephant National Park and Hluhluwe-iMfolozi Game Reserve, each contributing to the rich biodiversity of South Africa. Gain insights into conservation initiatives aimed at protecting endangered species and preserving the natural habitats that define the allure of the African safari.', '2023-03-02', '2023-03-02', 'Africa', '/articles/SouthAfrica.jpg'),
('Kiwi Wonders: A Journey Through the Natural Beauty of New Zealand', 1, 'Embark on a breathtaking journey through the enchanting landscapes of New Zealand, where snow-capped mountains, pristine lakes, and lush greenery create a canvas of natural wonders. ', 'New Zealand, a land of unparalleled beauty, invites travelers to discover its diverse and awe-inspiring landscapes. Begin your adventure in the Fiordland National Park, where Milford Sounds majestic fjords and waterfalls captivate the senses. Explore the geothermal wonders of Rotorua, where bubbling mud pools and geysers showcase the Earths natural forces. Journey to the vibrant city of Queenstown, surrounded by the Southern Alps, offering adrenaline-fueled activities and serene lake views. Immerse yourself in Maori culture, experiencing traditional haka performances and feasting on a hangi, a Maori-style feast cooked in the earth. New Zealands wonders are not just scenic; they are an invitation to connect with nature and embrace the spirit of the Kiwi way of life.', '2023-03-10', '2023-03-10', 'Oceania', '/articles/nz.jpg'),
('Down Under Discovery: Exploring Australias Diverse Landscapes', 2, 'Embark on an extraordinary journey across the vast continent of Australia, where diverse landscapes unfold, from the iconic Sydney Opera House to the rugged beauty of the Outback. ', 'Australia, a land of contrasts and natural marvels, invites travelers to explore its varied landscapes and vibrant cities. Begin your adventure in Sydney, where the iconic Opera House and Harbour Bridge stand as landmarks against the citys skyline. Immerse yourself in the eclectic arts scene and café culture of Melbourne, known for its street art and laneways. Venture into the heart of the continent to experience the vastness of the Australian Outback, with its red desert landscapes and iconic landmarks like Uluru. Dive into the mesmerizing underwater world of the Great Barrier Reef, encountering colorful coral reefs and a dazzling array of marine life. Australias allure lies not only in its iconic landmarks but also in the diversity of experiences waiting to be discovered across the continent.', '2023-03-11', '2023-03-11', 'Oceania', '/articles/AU.jpg'),
('Patagonian Wonders: A Wilderness Expedition', 3, 'Venture into the heart of Patagonia, where rugged landscapes, towering peaks, and pristine wilderness converge to create an adventurer''s paradise. ', 'Patagonia, with its dramatic scenery, is a haven for nature enthusiasts. The article explores the iconic Torres del Paine National Park, where granite peaks pierce the sky and azure lakes mirror the surrounding mountains. Readers are invited to embark on hikes through diverse ecosystems, encountering wildlife such as guanacos and Andean condors along the way. The narrative continues to the awe-inspiring glaciers of Los Glaciares National Park, where colossal ice formations calve into electric-blue lakes. Descriptions of rugged trails, remote landscapes, and the region''s unique wildlife paint a vivid picture of Patagonia''s untamed beauty.', '2023-04-02', '2023-04-02', 'America', '/articles/Pata.jpg'),
('A Cultural Odyssey Through the Streets of Marrakech', 1, 'Lose yourself in the vibrant tapestry of Marrakech, Morocco, where the bustling souks, historic palaces, and lively street performances create an immersive cultural experience. ', 'Marrakech, with its labyrinthine medina and lively street scenes, offers a sensory overload for travelers. The article captures the essence of Jemaa el-Fnaa, the main square, where snake charmers, musicians, and food vendors converge to create a vibrant spectacle. Readers are introduced to the intricate beauty of Bahia Palace, a masterpiece of Moroccan architecture adorned with colorful tiles and lush gardens. The narrative also dives into the world of traditional Moroccan cuisine, from aromatic tagines to sweet pastries enjoyed in bustling local markets.', '2023-04-03', '2023-04-03', 'Africa', '/articles/Macar.jpg'),
('Sailing the Turquoise Waters of the Greek Isles', 8, 'Embark on a nautical adventure through the azure waters of the Aegean Sea, where the Greek Isles beckon with their white-washed buildings, crystal-clear beaches, and ancient ruins. ', 'The Greek Isles offer a postcard-perfect setting for a maritime escapade. The article begins with the iconic Santorini, where white-washed buildings cling to cliffs overlooking the deep blue Aegean. Descriptions of sunsets over Oia and the vibrant atmosphere of Mykonos'' beaches create a vivid picture. The narrative then ventures to the largest Greek island, Crete, where Minoan ruins whisper tales of antiquity. Readers are invited to explore hidden coves, archaeological sites, and traditional villages, experiencing the diverse character of each island in the Cyclades.', '2023-04-05', '2023-04-05', 'Europe', '/articles/Greece.jpg'),
('Rediscovering the Silk Road: A Modern-Day Caravan', 8, 'This article unravels the cultural tapestry of Xi''ans Terracotta Army, explores the Islamic architecture of Samarkand, and crosses the deserts of Turkmenistan, revealing the shared heritage of civilizations along this epic transcontinental route.', 'The Silk Road, once a bustling network of trade routes, comes to life in this narrative. The article begins in Xi''an, China, where the Terracotta Army stands as a testament to the region''s rich past. Readers traverse through Central Asia, discovering the majestic beauty of Samarkand''s Islamic architecture and the cultural crossroads that shaped the Silk Road. Descriptions of desert landscapes, ancient caravanserais, and the historic city of Istanbul create a sense of adventure as the journey unfolds through the heart of Asia, uncovering the timeless allure of this legendary trade route.', '2023-04-21', '2023-04-21', 'Asia', '/articles/xian.jpg'),
('Discovering Paradise: The Islands of Fiji', 4, 'Explore the pristine beauty of Fiji, an archipelago in the heart of the South Pacific. ', 'Fiji, comprised of over 300 islands, captivates travelers with its diverse landscapes and warm hospitality. Begin your adventure in Nadi, where bustling markets and friendly locals set the tone. Cruise to the Yasawa Islands for postcard-perfect beaches and opportunities to snorkel among colorful marine life. For a cultural immersion, visit a traditional Fijian village, where you''ll witness the Meke dance and share a Kava ceremony with the locals. Explore the Garden of the Sleeping Giant, home to exotic orchids and native flora. Whether you''re seeking relaxation on the Coral Coast or thrilling encounters with sharks in Beqa Lagoon, Fiji offers a blend of tranquility and adventure. Embrace the "Bula Spirit" and let the enchanting islands of Fiji create lasting memories.', '2023-05-01', '2023-05-01', 'Oceania', '/articles/Fiji.jpg'),
('Beyond the Reef: Adventures in Papua New Guinea', 4, 'From the mystical Highlands to the underwater wonders of Milne Bay, this expedition unveils the hidden treasures of Oceania''s largest and most diverse nation. ', 'Papua New Guinea, with its rugged landscapes and vibrant tribal cultures, beckons intrepid travelers seeking authenticity. Start your exploration in the Highlands, where tribal traditions remain untouched by modernity. Engage with local communities, witness traditional singsings, and trek through lush valleys. Head to Milne Bay for world-class diving and snorkeling. The coral reefs teem with marine life, and the vibrant underwater landscapes are a photographer''s dream. Encounter the famous Baining Fire Dance in East New Britain, an awe-inspiring cultural performance. Navigate the Sepik River, where crocodile initiation ceremonies and elaborate spirit houses showcase the region''s unique customs. Papua New Guinea is a tapestry of experiences, where every encounter leaves an indelible mark on your journey through Oceania.', '2023-05-10', '2023-05-10', 'Oceania', '/articles/Papa.jpg'),
('The Enchanted Isles: Exploring Polynesia''s Marquesas', 6, 'Uncover the mysteries of the Marquesas Islands, a remote archipelago in French Polynesia.  ', 'The Marquesas, known as the "Land of Men," boast dramatic cliffs, lush valleys, and rugged coastlines. Begin your expedition in Nuku Hiva, the largest of the islands, where steep volcanic peaks dominate the skyline. Hike to the breathtaking Vaipo Waterfall and explore ancient petroglyphs at Hatiheu. Sail to Ua Pou, a haven for adventure enthusiasts with its towering spires and challenging hikes. Discover the artistry of Marquesan tattoos and traditional wood carving in Hiva Oa. Attend a traditional feast, or "umu," where local delicacies are prepared in an earth oven. The Marquesas Islands offer a glimpse into Polynesia''s ancient past, with sacred sites and untouched nature. This journey is a pilgrimage through a realm of mystique and beauty.', '2023-05-11', '2023-05-11', 'Oceania', '/articles/Island2.jpg'),
('Island Romance: A Getaway to Bora Bora', 6, 'Escape to the epitome of romance in Bora Bora, a jewel in the Society Islands of French Polynesia. ', 'Bora Bora, surrounded by a turquoise lagoon and coral reefs, is synonymous with luxury and romance. Check into an overwater bungalow, where the lapping waves become your lullaby. Snorkel in the lagoon''s vibrant coral gardens or embark on a shark and ray feeding excursion. Explore Matira Beach, renowned for its powder-soft sand and panoramic views. Indulge in a couples'' spa treatment with traditional Polynesian ingredients, and savor exquisite cuisine with your toes in the sand. For adventure seekers, hike Mount Otemanu for panoramic island views. Bora Bora is not just a destination for lovers; it''s a haven where the magic of the South Pacific comes to life.', '2023-05-12', '2023-05-12', 'Oceania', '/articles/Bora.jpg'),
('Enchanting Kyoto: Temples, Tea, and Tranquility', 1, 'Kyoto, Japan, stands as a testament to the country''s rich cultural heritage. This article invites you on a journey through Kyoto''s historic temples and traditional tea ceremonies. ', 'Kyoto, with its cherry blossom-lined streets and centuries-old traditions, is a destination that transports visitors to a bygone era. The article delves into the architectural marvels of Kinkaku-ji, where the Golden Pavilion reflects in still ponds, creating a scene of unparalleled beauty. Readers are invited to explore the vibrant torii gates of Fushimi Inari Shrine, a symbol of prosperity and good fortune. The narrative also explores the cultural significance of traditional tea ceremonies, highlighting the meditative atmosphere of tea houses nestled within lush gardens. The journey extends to Gion, Kyoto''s historic geisha district, where geisha performances captivate audiences with elegance and artistry.', '2023-03-12', '2023-03-12', 'Asia', '/articles/Kyoto2.jpg'),

('Vanuatu Vibes: Adventures in the South Pacific Archipelago', 5, 'Immerse yourself in the vibrant culture and natural wonders of Vanuatu, an archipelago of 83 islands in the South Pacific. ', 'Vanuatu, known for its friendly locals and diverse landscapes, invites exploration. Begin your journey in Port Vila, the capital, where markets burst with colorful produce and handmade crafts. Discover the hidden depths of the Blue Holes, crystal-clear freshwater springs surrounded by lush jungle. Tanna Island beckons with the fiery spectacle of Mount Yasur, one of the world''s most accessible active volcanoes. Witness traditional kastom ceremonies, where ancient customs come alive through dance and rituals. Snorkel or dive in the coral-rich waters of Espiritu Santo, home to the SS President Coolidge wreck. Vanuatu''s authenticity and natural beauty create a travel experience like no other in the heart of Oceania.', '2023-05-20', '2023-05-20', 'Oceania', '/articles/Island3.jpg'),
('Safari Serenity: Exploring the Maasai Mara in Kenya', 3, 'Embark on a safari adventure in the iconic Maasai Mara, Kenya''s wildlife haven.  ', 'The Maasai Mara, an extension of the Serengeti, is a wildlife spectacle like no other. Begin your safari with a sunrise game drive, where the golden hues paint the landscape and predators begin their daily hunt. Witness the Great Migration, a breathtaking display of wildebeests, zebras, and other ungulates crossing the Mara River. Explore the conservancies surrounding the Mara for intimate wildlife encounters, from lion prides to elusive leopards. Engage with the Maasai people, known for their vibrant culture and traditional ceremonies. The Maasai Mara is a sanctuary for nature enthusiasts seeking a front-row seat to the drama of the African wilderness.', '2023-05-21', '2023-05-21', 'Africa', '/articles/lion.jpg'),
('Majestic Victoria Falls: The Jewel of Southern Africa', 5, 'Discover the awe-inspiring beauty of Victoria Falls, a natural wonder that straddles the border between Zambia and Zimbabwe.   ', 'Victoria Falls, known as "The Smoke That Thunders," is a testament to the raw power of nature. Begin your exploration on the Zimbabwean side for panoramic views of the falls. Feel the mist on your face as you walk along the mist-soaked trails, surrounded by a lush rainforest that teems with wildlife. Cross the border to Zambia for a different perspective and the chance to take a dip in the famous Devil''s Pool, perched on the edge of the falls. Sunset boat cruises on the Zambezi River provide a serene contrast to the thunderous energy of the falls. Victoria Falls is more than a sight; it''s a sensory journey through the heart of Africa.', '2023-05-22', '2023-05-22', 'Africa', '/articles/Falls.jpg'),

('Cultural Odyssey: Exploring Morocco''s Imperial Cities', 6, 'Embark on a cultural odyssey through Morocco''s Imperial Cities, where history, architecture, and vibrant marketplaces create a tapestry of experiences. ', 'Morocco''s Imperial Cities—Marrakech, Fes, Meknes, and Rabat—reflect the country''s diverse history and cultural influences. Start your journey in Marrakech, where the bustling Jemaa el-Fnaa square comes alive with street performers, storytellers, and traditional musicians. In Fes, wander through the labyrinthine streets of the medina, home to the world''s oldest university, the University of Al Quaraouiyine. Explore the ancient Roman ruins of Volubilis near Meknes, and delve into the political capital, Rabat, with its historic Kasbah of the Udayas. Immerse yourself in Moroccan hospitality, savor traditional cuisine, and shop for intricate handicrafts in the vibrant souks. Morocco''s Imperial Cities offer a captivating blend of past and present.', '2023-06-01', '2023-06-01', 'Africa', '/articles/city.jpg'),
('Enchanting Cinque Terre: A Coastal Odyssey in Italy', 10, 'Embark on a journey along the rugged Italian Riviera to discover the colorful villages of Cinque Terre. ', 'Cinque Terre, a UNESCO World Heritage site, comprises five picturesque villages clinging to the cliffs overlooking the Mediterranean. Begin your exploration in Riomaggiore, where pastel-hued houses cascade down to the harbor. Hike the scenic coastal trail that connects each village, passing through terraced vineyards and olive groves. Indulge in local cuisine at waterfront trattorias, savoring freshly caught seafood and Ligurian specialties. Explore the medieval charm of Vernazza and the artistic allure of Corniglia. Conclude your journey in Monterosso, where sandy beaches invite relaxation. Cinque Terre is a symphony of colors and flavors that lingers in the heart.', '2023-06-02', '2023-06-02', 'Europe', '/articles/Italy.jpg'),
('Breathtaking Scottish Highlands: A Journey Through Nature''s Masterpiece', 10, 'Uncover the untamed beauty of the Scottish Highlands, where mist-covered mountains, serene lochs, and ancient castles create a landscape that captivates the soul. ', 'The Scottish Highlands, a realm of myths and legends, beckon adventurers seeking solitude in nature''s embrace. Begin your journey in Inverness, the gateway to the Highlands, and follow the North Coast 500 route through ever-changing landscapes. Marvel at the dramatic peaks of Ben Nevis and the enchanting beauty of Glencoe. Explore historic castles like Eilean Donan, perched on the shores of Loch Duich, and delve into the mysterious depths of Loch Ness. Hike through ancient Caledonian pine forests, home to red deer and elusive wildlife. The Scottish Highlands offer a sanctuary for those yearning for the serenity of wide-open spaces.', '2023-06-03', '2023-06-03', 'Europe', '/articles/Scotland.jpg'),
('Venice: A Floating Masterpiece on the Adriatic', 2, 'Step into the romantic realm of Venice, a city of canals, historic architecture, and timeless elegance.  ', 'Venice, a city built on water, invites travelers to navigate its labyrinthine canals aboard iconic gondolas. Begin your journey in Piazza San Marco, surrounded by architectural marvels like St. Mark''s Basilica and the Campanile. Cross the Rialto Bridge to explore the bustling markets and artisan workshops. Wander through the quiet neighborhoods of Dorsoduro and Cannaregio, discovering hidden gems and local trattorias. Visit the Peggy Guggenheim Collection for a dose of modern art, and attend a traditional opera performance for a taste of Venetian culture. Venice is a floating masterpiece where every corner tells a story of romance and history. ', '2023-06-04', '2023-06-04', 'Europe', '/articles/Venice.jpg');



INSERT INTO comments (parent_id, article_id, user_id, content, time)
VALUES
  (NULL, 1, 5, "Exploring Cambodia and venturing into Myanmar's Shan State is an adventurous journey I'd love to take. Hill tribes preserving traditions sound fascinating and authentic.", '2023-02-04 15:00:18'),
  (NULL, 2, 2, 'I like this Beautiful pictures!', '2023-03-01 19:00:13'),
  (NULL, 1, 3, 'I like this article.', '2023-02-05 01:45:23'),
  (3, 1, 6, 'Great article!', '2023-02-05 09:56:45'),
  (3, 1, 9, 'Same! I would like to go and visit someday!', '2023-03-06 05:13:21'),
  (NULL, 3, 5, 'I love Kyoto!', '2023-04-01 13:43:23'),
  (2, 2, 4, 'We should go together!', '2023-03-01 14:43:45'),
  (NULL, 1, 2, 'I visited there last month.Nice place!', '2023-04-20 08:50:53'),
  (NULL, 4, 6, 'Great View of Himalaya', '2023-09-03 07:21:24' ),
  (1, 1, 4, "Exploration is more than just ticking off places. The idea of going beyond the usual and truly connecting with the essence of Southeast Asia resonates deeply with me.", '2023-05-01 19:20:00'),
  (10, 1, 7, "Count me in! The invitation to readers feels personal. I'm ready to embark on this extraordinary journey and create my own Southeast Asian stories.", "2023-06-04 15:15:00"),
  (11, 1, 8, "Imagining the adventure feels like taking a mental vacation. Can't wait for the day when these images become my reality!", "2023-06-10 13:43:23"),
  (6, 3, 6, "Let's go in the break!", '2023-04-05 10:32:12'),
  (13, 3, 7, "I'm packing now!", '2023-04-05 11:13:25'),
  (14, 3, 4, "Ticket done!🌟✈️", '2023-04-05 14:13:20');


INSERT INTO likes (article_id, user_id)
VALUES
  (1, 3),
  (1, 4),
  (1, 2),
  (1, 8),
  (2, 1),
  (2, 6),
  (2, 7),
  (3, 9),
  (3, 5),
  (3, 10),
  (4, 4),
  (4, 2),
  (4, 3),
  (5, 8),
  (5, 9),
  (5, 6),
  (5, 5),
  (6, 1),
  (6, 8),
  (6, 9);



